id: P009587
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W30419
  title: བསླབ་བྱ་རྣམ་སྲས་གན་མཛོད།
  author: ''
  volumes:
    e20c413bd9af48769153e62e3a887b5f:
      image_group_id: I1KG23231
      title: ''
      volume_number: 1
      total_pages: 182
      base_file: v001.txt
