id: IE6177AEB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T12:38:20+00:00'
last_modified: '2022-06-08T12:05:08.548621+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30419
  title: བསླབ་བྱ་རྣམ་སྲས་གན་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    96E0:
      image_group_id: I1KG23231
      title: ''
      total_pages: 182
      order: 1
      base_file: 96E0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
